Add docker-compose file for local development
nhsuk/nhsuk-rancher-templates pull request #1
Opened 2017-01-25 16:21 UTC by adamgraves-choices

2017-01-26 08:39 UTC, st3v3nhunt requested changes
When running with default values either set in the shell or within a `.env` file I get the error:
`ERROR: Invalid interpolation format for "<section>"...`. The way the default values are being set just doesn't seem to want to work.

I've had a look online and i've not found anything that suggests it shouldn't work. However, how about having the `.env` set with the defaults rather than them being in `docker-compose.yml`?

2017-01-26 08:39 UTC, st3v3nhunt commented on templates/c2s_local_dev/README.md
> +1. Clone this repo locally `git https://github.com/nhsuk/nhsuk-rancher-templates.git`
You might want to add `clone` to that command e.g. `git clone https://github.com/nhsuk/nhsuk-rancher-templates.git`

2017-01-26 08:39 UTC, st3v3nhunt commented on templates/c2s_local_dev/README.md
> +4. Run `docker-compose up --build --force-recreate`. This will bring up your "stack" with port 3000 exposed locally. The `--build` and `--force-recreate` will ensure you always start the stack from s
:+1: Good info

2017-01-31 15:52 UTC, neilbmclaughlin commented
No longer required - later branch includes these commits

2017-01-31 15:52 UTC, closed without merging