:cow: mongo templates
nhsuk/nhsuk-rancher-templates pull request #13
Opened 2017-02-09 21:31 UTC by beseven

A couple of issues/caveats:
- not sure if traefik and c2s-lb requires a 1 folder too - as based on what I've seen - they don't seem to change from 0
- I don't have a healthcheck for the mongo image; looking at rancher catalogue - there are only recipes for health checks for a cluster

2017-02-09 21:36 UTC, beseven commented on templates/c2s-pharmacy-finder/1/docker-compose.yml
> +      NODE_ENV: production
Mmm - http://unix.stackexchange.com/questions/32001/what-is-m-and-how-do-i-get-rid-of-it 
This is what happens when I Copy+Paste config from @adamgraves-choices

2017-02-10 09:34 UTC, st3v3nhunt requested changes

2017-02-10 09:34 UTC, st3v3nhunt commented on templates/c2s-pharmacy-finder/1/docker-compose.yml
> +      traefik.port: 3001
Port 27017 for Mongo

2017-02-10 09:34 UTC, st3v3nhunt commented on templates/c2s-pharmacy-finder/1/rancher-compose.yml
> +  start_on_create: true
This health check should be ok for Mongo:

```
health_check:
  response_timeout: 60000
  healthy_threshold: 2
  port: 271017
  unhealthy_threshold: 3
  initializing_timeout: 60000
  interval: 20000
  strategy: recreate
  request_line: ''
  reinitializing_timeout: 60000
```

2017-02-10 09:34 UTC, st3v3nhunt commented on templates/c2s-pharmacy-finder/1/rancher-compose.yml
> +      label: "nearby-services-api Docker image tag:"
Label value should be `mongodb_pharmacy Docker image tag:` (assuming the same pattern employed as other questions)

2017-02-10 11:11 UTC, beseven commented on templates/c2s-pharmacy-finder/1/docker-compose.yml
> +      traefik.port: 3001
👍

2017-02-10 14:03 UTC, st3v3nhunt approved these changes

2017-02-10 14:03 UTC, merged