:octopus: Changes required for CI scripts
nhsuk/nhsuk-rancher-templates pull request #14
Opened 2017-02-10 09:27 UTC by neilbmclaughlin

The CI scripts need to build an answers file for use with the `rancher
up` command and only have the repo names available.

The paramater names have been changed to match the repo names.

2017-02-13 09:05 UTC, beseven approved these changes
LOTM

2017-02-13 11:39 UTC, st3v3nhunt requested changes
These changes have been made in the `0` version. Should they have been done in `1`?
This branch is behind `master` and is probably worth rebasing.

2017-02-13 18:24 UTC, neilbmclaughlin commented
Not sure of the versioning best practice. I guess we should increment the version each time, so perhaps, these changes should be in '2'.

Also, not sure if we can or should be doing this through GitHub's release tagging in order to avoid hard coding versions in the URL's used in the CI scripts.

Issue raised [here](https://github.com/nhsuk/ci-deployment/issues/8)

2017-02-15 11:22 UTC, neilbmclaughlin commented
As discussed, I'm going to move the mongo db changes in version 2 (folder 1) into version 1 (folder 0) so we can carry on using the hard coded /0 in the curl path in the CI scripts.

This means we can not easily create a stack with the old services but it is not likely we will need to do this. Should we need to we can either roll back or create a branch for the pre-mongo version of the templates and add a new catalog entry using the URL for the branch.

2017-02-23 08:18 UTC, neilbmclaughlin commented
@st3v3nhunt - changed to remove the c2s-pharmacy-finder  '1' directory after ensuring any commits in 1 were reflected in 0. This should be to merge now.

2017-02-23 08:56 UTC, st3v3nhunt requested changes
Looks good.

Question about the consistency of the description and label of the questions in the rancher-compose for the docker image tags. There is a mix of `_`, ` ` and `-` used. I know it isn't important from the system's POV but can these be consistent between the 3 questions for the images of the api, web app and db?

2017-02-23 08:57 UTC, beseven commented
Re-looked at changes and they seem sensible to me!

2017-03-03 08:44 UTC, st3v3nhunt commented
@neilbmclaughlin Is this PR still valid? If so can it be rebased please and the last comment addressed. Thanks!

2017-03-03 12:54 UTC, neilbmclaughlin commented
@st3v3nhunt - good to merge. Once done then any builds which have `RANCHER_TEMPLATE_BRANCH_NAME ` defined will need it deleting. I'll do that for connecting to services and gp-finder.

2017-03-03 12:55 UTC, neilbmclaughlin commented
The latest version of the CI PR script now handles multiple template versions in order to get the latest.

2017-03-06 08:53 UTC, st3v3nhunt approved these changes

2017-03-06 08:53 UTC, merged