:persevere: add db info to template
nhsuk/nhsuk-rancher-templates pull request #28
Opened 2017-02-23 17:37 UTC by beseven

2017-02-23 17:47 UTC, st3v3nhunt requested changes
I think the variable name needs updating

2017-02-23 17:47 UTC, st3v3nhunt commented on templates/c2s-gp-finder/0/rancher-compose.yml
> +    - variable: "gp_finder_db_docker_image_tag"
The variable will need to be `profiles_db_docker_image_tag` for it to work with the CI scripts. @neilbmclaughlin can you confirm?
If it does, probably the description and label here will want to be updated along with where it is used in `docker-compose` i.e. https://github.com/nhsuk/nhsuk-rancher-templates/pull/28/files#diff-a5f45e5d628f0630d457041224a3c35eR23

2017-02-23 18:05 UTC, neilbmclaughlin requested changes

2017-02-23 18:05 UTC, neilbmclaughlin commented on templates/c2s-gp-finder/0/docker-compose.yml
> +      io.rancher.container.pull_image: always
New line.

2017-02-23 18:05 UTC, neilbmclaughlin commented on templates/c2s-gp-finder/0/rancher-compose.yml
> +    - variable: "gp_finder_db_docker_image_tag"
@st3v3nhunt is right. If you are using the profiles db then the variable will need to be called `profiles_db_docker_image_tag` for the CI scripts to work. 

If we change to having a _gp-finder-db_ repo with the Dockerfile extending the profiles db image to add the geospatial index we will use the `gp_finder_db_docker_image_tag` form. 

See the readme in [PR4](https://github.com/nhsuk/ci-deployment/pull/4) for more details on the naming conventions we currently employ.

2017-02-24 23:09 UTC, st3v3nhunt approved these changes
Approved against [4574c89](https://github.com/nhsuk/nhsuk-rancher-templates/pull/28/commits/4574c8919ad32e231e899a1c07e2e21390e4ce78)

2017-02-27 10:31 UTC, neilbmclaughlin commented
Approved against 4574c89

2017-02-27 10:31 UTC, neilbmclaughlin approved these changes

2017-02-27 10:31 UTC, merged